/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmPrincipal.java
 *
 * Created on 24-feb-2009, 16:04:34
 */

package GUI;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administrador
 */
public class frmPrincipal extends javax.swing.JFrame {
    private static  frmPrincipal peds = null;
    
        intFrmMoviles vMoviles = null;
        intFrmArticulos vArts = null;
        intFrmClientes vCli = null;
        intFrmPedidosAsignados vPedsAsign= null;
    /** Creates new form frmPrincipal */
    private frmPrincipal(){
        intFrmPedidos ventPedidos = intFrmPedidos.getInstancia();
        initComponents();
        jDesktopPane1.add(ventPedidos);
        ventPedidos.setVisible(true);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    public static frmPrincipal getInstancia() {
        if(peds==null){
            peds=new frmPrincipal();
        }
        return peds;
    }

    public void mostarPedidos(){
        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuPedsEntregados = new javax.swing.JMenu();
        mnuMoviles = new javax.swing.JMenu();
        mnuArticulos = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Mantenimiento de Pedidos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        mnuPedsEntregados.setText("Pedidos entregados");
        mnuPedsEntregados.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnuPedsEntregadosMenuSelected(evt);
            }
        });
        jMenuBar1.add(mnuPedsEntregados);

        mnuMoviles.setText("Moviles");
        mnuMoviles.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnuMovilesMenuSelected(evt);
            }
        });
        jMenuBar1.add(mnuMoviles);

        mnuArticulos.setText("Articulos");
        mnuArticulos.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnuArticulosMenuSelected(evt);
            }
        });
        jMenuBar1.add(mnuArticulos);

        mnuClientes.setText("Clientes");
        mnuClientes.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnuClientesMenuSelected(evt);
            }
        });
        jMenuBar1.add(mnuClientes);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuPedsEntregadosMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnuPedsEntregadosMenuSelected
         mostrarPedidosAsignados();
}//GEN-LAST:event_mnuPedsEntregadosMenuSelected

    private void mnuMovilesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnuMovilesMenuSelected
       vMoviles = intFrmMoviles.getInstancia();
        vMoviles.setVisible(true);

        vMoviles.toFront();
        vMoviles.setAlwaysOnTop(true);
    }//GEN-LAST:event_mnuMovilesMenuSelected

    private void mnuArticulosMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnuArticulosMenuSelected
        vArts = intFrmArticulos.getInstancia();
        vArts.setVisible(true);
        vArts.toFront();
        vArts.setAlwaysOnTop(true);
    }//GEN-LAST:event_mnuArticulosMenuSelected

    private void mnuClientesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnuClientesMenuSelected
        vCli = intFrmClientes.getInstancia();
        vCli.setVisible(true);
        vCli.toFront();
        vCli.setAlwaysOnTop(true);
    }//GEN-LAST:event_mnuClientesMenuSelected
public void mostrarPedidosAsignados(){
        vPedsAsign = intFrmPedidosAsignados.getInstancia();
        vPedsAsign.setVisible(true);
        vPedsAsign.setFocusable(true);
        vPedsAsign.toFront();
        vPedsAsign.setAlwaysOnTop(true);
        
        

}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnuArticulos;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuMoviles;
    private javax.swing.JMenu mnuPedsEntregados;
    // End of variables declaration//GEN-END:variables

}
