/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * intFrmPedidosAsignados.java
 *
 * Created on 23/03/2009, 08:36:44 AM
 */

package GUI;

import ca.odell.glazedlists.BasicEventList;
import ca.odell.glazedlists.EventList;
import ca.odell.glazedlists.swing.EventTableModel;
import dominio.Articulos;
import dominio.Cliente;
import dominio.Pedidos;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import persistencia.Persistir;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
/**
 *
 * @author Docente
 */
public class intFrmPedidosAsignados extends javax.swing.JFrame implements ActionListener{
    DefaultTableModel modelo = new DefaultTableModel();
    Vector headVector=new Vector(10);
    DateCellRenderer renderD = new DateCellRenderer();
    private static  intFrmPedidosAsignados peds = null;
    AutoResizeTable tblRes = AutoResizeTable.getInstancia();
    EventList<Pedidos> pedList = new BasicEventList<Pedidos>();
    private static final String ACTION_CLOSE = "ACTION_CLOSE";
    /** Creates new form intFrmPedidosAsignados */
private intFrmPedidosAsignados() {
        initComponents();
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        int colDate=1;
        pedList = recorrerLista();
        PedidosEntTableFormat tblPed = new PedidosEntTableFormat();
        EventTableModel<Pedidos> PedTableModel = new EventTableModel(pedList, tblPed);
        jTable1.setModel(PedTableModel);
        TableColumn col = jTable1.getColumnModel().getColumn(colDate);
        col.setCellRenderer(renderD);
        jTable1 = tblRes.autoResizeColWidth(jTable1, PedTableModel);
        jTable1.setSelectionForeground(Color.RED);
        
    }

public EventList recorrerLista(){
        Persistir p = Persistir.getInstancia();
        Vector<Pedidos> lista2 = p.listarPedidosAsignados();
        Iterator it = lista2.iterator();
        while(it.hasNext()){
            Vector v = new Vector();
            v = (Vector) it.next();
            int index = (Integer)v.get(0);
            Pedidos ped = new Pedidos();
            ped = p.buscarPedidoPorId(index);
            pedList.add(ped);
        }
        return pedList;

    }

    public static intFrmPedidosAsignados getInstancia(){
        if(peds==null){
            peds=new intFrmPedidosAsignados();
        }
        return peds;
    }

    public void agregarFilaPedido(Pedidos p){
        pedList.add(p);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        PedidosPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("PedidosPU").createEntityManager();
        articulosQuery = java.beans.Beans.isDesignTime() ? null : PedidosPUEntityManager.createQuery("SELECT a FROM Articulos a");
        articulosList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : articulosQuery.getResultList();
        movilesQuery = java.beans.Beans.isDesignTime() ? null : PedidosPUEntityManager.createQuery("SELECT m FROM Moviles m");
        movilesList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : movilesQuery.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public Component prepareRenderer(TableCellRenderer renderer, int rowIndex, int vColIndex) {
                Component c = super.prepareRenderer(renderer, rowIndex, vColIndex);

                if (rowIndex % 2 == 0 && !isCellSelected(rowIndex, vColIndex)) {
                    java.awt.Color color = new java.awt.Color(242, 249, 255);
                    c.setBackground(color);
                } else {
                    // If not shaded, match the table's background
                    java.awt.Color color = new java.awt.Color(216, 230, 230);
                    c.setBackground(color);
                }
                return c;
            }}
            ;
            jLabel10 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel11 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            lblNombreenPedido = new javax.swing.JLabel();
            txtMovil = new javax.swing.JTextField();
            jLabel12 = new javax.swing.JLabel();
            cboArticulos = new javax.swing.JComboBox();
            lblFecha = new javax.swing.JLabel();
            txtProxMov = new javax.swing.JTextField();
            txtFlete = new javax.swing.JTextField();
            jLabel9 = new javax.swing.JLabel();
            txtCantidad = new javax.swing.JTextField();
            btnBorrarPedido = new javax.swing.JButton();
            jLabel8 = new javax.swing.JLabel();
            jRadioButton1 = new javax.swing.JRadioButton();
            jRadioButton2 = new javax.swing.JRadioButton();
            jLabel1 = new javax.swing.JLabel();
            btnActualizarPed = new javax.swing.JButton();
            txtObservaciones = new javax.swing.JTextField();

            setTitle("Pedidos Asignados");

            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTable1MouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(jTable1);

            jLabel10.setText("Observaciones:");

            jLabel6.setText("Fecha:");

            jLabel11.setText("Móvil:");

            jLabel7.setText("Articulo:");

            jLabel5.setText("Nombre:");

            lblNombreenPedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            jLabel12.setText("Prox Movil:");

            org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, articulosList, cboArticulos);
            bindingGroup.addBinding(jComboBoxBinding);

            cboArticulos.setRenderer(new DefaultListCellRenderer() {
                @Override
                public Component getListCellRendererComponent(
                    JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                    super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                    if (value instanceof dominio.Articulos) {
                        Articulos art = (Articulos)value;
                        setText(art.getNombre());
                    }
                    return this;
                }
            });

            lblFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            jLabel9.setText("Flete:");

            btnBorrarPedido.setText("Eliminar Pedido");
            btnBorrarPedido.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnBorrarPedidoActionPerformed(evt);
                }
            });

            jLabel8.setText("Cantidad:");

            jRadioButton1.setText("Asignado");

            jRadioButton2.setText("Pendiente");
            jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jRadioButton2ActionPerformed(evt);
                }
            });

            jLabel1.setText("Estado del Pedido:");

            btnActualizarPed.setText("Actualizar datos del pedido");
            btnActualizarPed.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnActualizarPedActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel11)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtProxMov, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblNombreenPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtFlete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cboArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jRadioButton1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton2))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnBorrarPedido)
                                    .addGap(179, 179, 179)
                                    .addComponent(btnActualizarPed)))))
                    .addContainerGap(332, Short.MAX_VALUE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnActualizarPed)
                                .addComponent(btnBorrarPedido))
                            .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(7, 7, 7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtFlete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(txtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(txtProxMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(cboArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lblNombreenPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(145, Short.MAX_VALUE))
            );

            bindingGroup.bind();

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarPedidoActionPerformed
        Persistir p = Persistir.getInstancia();
        int row = jTable1.getSelectedRow();
        Integer val =(Integer) jTable1.getValueAt(row, 0);
        Pedidos ped = new Pedidos();
        int id =val;
        ped = p.buscarPedidoPorId(id);
        p.eliminarPedido(ped);
        pedList.remove(ped);
        
    }//GEN-LAST:event_btnBorrarPedidoActionPerformed


    private void btnActualizarPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPedActionPerformed
        Persistir p = Persistir.getInstancia();
        int row = jTable1.getSelectedRow();
        Integer val =(Integer) jTable1.getValueAt(row, 0);
        Pedidos ped = new Pedidos();
//        Articulos art = new Articulos();
//        art=(Articulos) cboArticulos.getSelectedItem();
        int id =val;
        ped = p.buscarPedidoPorId(id);
//        ped.setMovilAsignado((Moviles) cboMoviles.getSelectedItem());
//
//        ped.setCantidad(Integer.parseInt(txtCantidad.getText()));
//        ped.setFlete(Integer.parseInt(txtFlete.getText()));
//        ped.setIdArticulo(art);
//        ped.setMovilAsignado((Moviles) cboMoviles.getSelectedItem());
//        ped.setObservaciones(txtObservaciones.getText());
//        Cliente cli = ped.getIdcliente();
        if (jRadioButton1.isSelected()){
//                ped.setEntregado('E');
//            jTable1.setValueAt(ped.getId(), row, 0);
//            jTable1.setValueAt(ped.getFechaPedido(), row, 1);
//            jTable1.setValueAt(cli.getApellidonombre(), row, 2);
//            jTable1.setValueAt(cli.getDireccion(), row, 3);
//            jTable1.setValueAt(art.getNombre(), row, 4);
//            jTable1.setValueAt(ped.getIdMovil(), row, 5);
//            jTable1.setValueAt(ped.getIdMovil2(), row, 6);
//            jTable1.setValueAt(ped.getCantidad(), row, 7);
//            jTable1.setValueAt(ped.getFlete(), row, 8);
//            jTable1.setValueAt(ped.getTotal(), row, 9);
//            jTable1.setValueAt(ped.getEntregado(), row, 10);
//            jTable1.setValueAt(ped.getMovilAsignado(), row, 11);
        }
        else
            if(jRadioButton2.isSelected()){

                Integer val2 =(Integer) jTable1.getValueAt(row, 0);
                ped = p.buscarPedidoPorId(val2);
                ped.setEntregado('P');

                pedList.remove(ped);
                intFrmPedidos.getInstancia().insertarFilaPedidos(ped);
            }
//        int total;
//        int precio;
//        int cantidad;
//        precio = art.getPrecio();
//        cantidad = ped.getCantidad();
//        total = precio * cantidad + ped.getFlete();
//        ped.setTotal();
//        p.actualizarPedido(ped);

        
}//GEN-LAST:event_btnActualizarPedActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        Persistir p = Persistir.getInstancia();
        int row = jTable1.getSelectedRow();
        Integer val =(Integer) jTable1.getValueAt(row, 0);
        Pedidos ped = new Pedidos();
        int id =val;
        ped = p.buscarPedidoPorId(id);
        Cliente cli = new Cliente();
        cli=ped.getIdcliente();
        txtCantidad.setText(String.valueOf(ped.getCantidad()));
        txtFlete.setText(String.valueOf(ped.getFlete()));
        txtMovil.setText(ped.getIdMovil().toString());
        txtObservaciones.setText(String.valueOf(ped.getObservaciones()));
        txtProxMov.setText(String.valueOf(ped.getIdMovil2()));
        lblFecha.setText(String.valueOf(ped.getFechaPedido()));
        lblNombreenPedido.setText(cli.getApellidonombre());
//        cboMoviles.setSelectedItem(ped.getMovilAsignado());
        cboArticulos.setSelectedItem(ped.getIdArticulo());
        if (ped.getEntregado()=='E')
            jRadioButton1.setSelected(true);
        else
            jRadioButton2.setSelected(true);
        cboArticulos.setSelectedItem(ped.getIdArticulo());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        Persistir p = Persistir.getInstancia();
        int row = jTable1.getSelectedRow();
        Integer val =(Integer) jTable1.getValueAt(row, 0);
        Pedidos ped = new Pedidos();
        int id =val;
        ped = p.buscarPedidoPorId(id);
        ped.setEntregado('P');
        p.actualizarPedido(ped);
        pedList.remove(ped);
        intFrmPedidos.getInstancia().insertarFilaPedidos(ped);
    }//GEN-LAST:event_jRadioButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager PedidosPUEntityManager;
    private java.util.List<dominio.Articulos> articulosList;
    private javax.persistence.Query articulosQuery;
    private javax.swing.JButton btnActualizarPed;
    private javax.swing.JButton btnBorrarPedido;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboArticulos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombreenPedido;
    private java.util.List<dominio.Moviles> movilesList;
    private javax.persistence.Query movilesQuery;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFlete;
    private javax.swing.JTextField txtMovil;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtProxMov;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
public void actionPerformed(ActionEvent e) {
        if(ACTION_CLOSE.equals(e.getActionCommand())) {
            setVisible(false);
            dispose();
        }
    }

    @Override
    protected JRootPane createRootPane() {
        JRootPane rootPane = new JRootPane();
        int menuShortcutKey = Toolkit.getDefaultToolkit().getMenuShortcutKeyMask();
        KeyStroke w = KeyStroke.getKeyStroke(KeyEvent.VK_W, menuShortcutKey);
        KeyStroke esc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        rootPane.registerKeyboardAction(this, ACTION_CLOSE, w, JComponent.WHEN_IN_FOCUSED_WINDOW);
        rootPane.registerKeyboardAction(this, ACTION_CLOSE, esc, JComponent.WHEN_IN_FOCUSED_WINDOW);
        return rootPane;
    }
}
