/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * intFrmArticulos.java
 *
 * Created on 10/03/2009, 08:57:24 AM
 */

package GUI;

import java.awt.event.ActionEvent;
import persistencia.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ca.odell.glazedlists.*;
import ca.odell.glazedlists.BasicEventList;
import ca.odell.glazedlists.swing.*;
import dominio.Articulos;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;


/**
 *
 * @author Docente
 */
public class intFrmArticulos extends javax.swing.JFrame implements ActionListener{

    DefaultTableModel modelo = new DefaultTableModel();
    AutoResizeTable tblRes = AutoResizeTable.getInstancia();
    Vector headVector = new Vector(4);
    private static intFrmArticulos arts;
    List lista = Persistir.getInstancia().listarArticulos();
    Iterator it = lista.iterator();
    private EventList<Articulos> artList = new BasicEventList<Articulos>() ;
    Persistir p = Persistir.getInstancia();
    private static final String ACTION_CLOSE = "ACTION_CLOSE";
    Collection<Articulos> lista2;

    /** Creates new form intFrmArticulos */
    private intFrmArticulos() {
        initComponents();
        lista2 = p.listarArticulos2();
        artList.addAll(lista2);
        ArticulosTableFormat tblArt = new ArticulosTableFormat();
        EventTableModel<Articulos> artTableModel = new EventTableModel(artList, tblArt);
        jTable1.setModel(artTableModel);
        

    }

    public static intFrmArticulos getInstancia(){
        if(arts==null){
            arts=new intFrmArticulos();
        }
        return arts;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtKg = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnBorrarArt = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnActualizarArt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento de Artículos");

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Precio:");

        jLabel4.setText("Kgs:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBorrarArt.setText("Borrar Artículo");
        btnBorrarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarArtActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/logo_acodike.gif"))); // NOI18N
        jLabel13.setText("jLabel13");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        btnActualizarArt.setText("Actualizar");
        btnActualizarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarArtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtKg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGuardar))
                                .addComponent(txtNom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnActualizarArt))))
                    .addComponent(btnBorrarArt))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar)
                            .addComponent(btnActualizarArt)))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrarArt)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
//        Persistir p = Persistir.getInstancia();
        Articulos a = new Articulos();
        if (txtCod.getText().isEmpty() || txtKg.getText().isEmpty() || txtNom.getText().isEmpty() || txtPrecio.getText().isEmpty())
            JOptionPane.showMessageDialog(null,"Debe llenar todos los datos");
        else{
        a.setCodigo(Integer.parseInt(txtCod.getText()));
        a.setKgs(Integer.parseInt(txtKg.getText()));
        a.setNombre(txtNom.getText());
        a.setPrecio(Integer.parseInt(txtPrecio.getText()));
        p.guardar(a);
        artList.add(a);
//        actualizarGrilla();
        intFrmPedidos.getInstancia().agregarArt(a);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBorrarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarArtActionPerformed
//        Persistir p = Persistir.getInstancia();
        int row = jTable1.getSelectedRow();
        Integer val =(Integer) jTable1.getValueAt(row, 0);
        Articulos art = new Articulos();
        int id =val;
        art = p.buscarArticulosPorID(id);
        p.eliminarArticulo(art);
        artList.remove(art);
        intFrmPedidos.getInstancia().borrarArt(art);

    }//GEN-LAST:event_btnBorrarArtActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        p = Persistir.getInstancia();
        int row = jTable1.getSelectedRow();
        Integer val =(Integer) jTable1.getValueAt(row, 0);
        Articulos art = new Articulos();
        int id =val;
        art = p.buscarArticulosPorID(id);
        txtCod.setText(String.valueOf(art.getCodigo()));
        txtKg.setText(String.valueOf(art.getKgs()));
        txtNom.setText(art.getNombre());
        txtPrecio.setText(String.valueOf(art.getPrecio()));
        if(!areFieldsEmpty())
            btnGuardar.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private boolean areFieldsEmpty(){
        if(txtCod.getText().isEmpty()){
            return true;
        }
        else{
            return false;
        }
    }
    private void btnActualizarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarArtActionPerformed
        p = Persistir.getInstancia();
        Articulos art = p.buscarArticulosPorID(Integer.valueOf(txtCod.getText()));
        art.setKgs(Integer.valueOf(txtKg.getText()));
        art.setNombre(txtNom.getText());
        art.setPrecio(Integer.valueOf(txtPrecio.getText()));
        p.actualizarArticulo(art);
        lista2 = Persistir.getInstancia().listarArticulos2();
        artList.clear();
        artList.addAll(lista2);
         if(!areFieldsEmpty()){
             txtCod.setText("");
             txtKg.setText("");
             txtNom.setText("");
             txtPrecio.setText("");
             btnGuardar.setEnabled(true);
         }
    }//GEN-LAST:event_btnActualizarArtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarArt;
    private javax.swing.JButton btnBorrarArt;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtKg;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    public void actionPerformed(ActionEvent e) {
        if(ACTION_CLOSE.equals(e.getActionCommand())) {
            setVisible(false);
            dispose();
        }
    }

    @Override
    protected JRootPane createRootPane() {
        JRootPane jrootPane = new JRootPane();
        int menuShortcutKey = Toolkit.getDefaultToolkit().getMenuShortcutKeyMask();
        KeyStroke w = KeyStroke.getKeyStroke(KeyEvent.VK_W, menuShortcutKey);
        KeyStroke esc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        jrootPane.registerKeyboardAction(this, ACTION_CLOSE, w, JComponent.WHEN_IN_FOCUSED_WINDOW);
        jrootPane.registerKeyboardAction(this, ACTION_CLOSE, esc, JComponent.WHEN_IN_FOCUSED_WINDOW);
        return jrootPane;
    }

   

}
